config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tweet/list' => 'tweets#list'
  resources :tweets do
   resources :likes, only: [:create, :destroy]
   resources :comments, only: [:create]
  
  end 
   resources :perfumes
  root 'tweets#index'
  get 'users' =>'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user  
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets  
  has_many :comments, dependent: :destroy     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :overall,:level)
    end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
   
    def index
    end

    def new
        @perfume = Perfume.new
    end

    def show
        @perfume = Perfume.find_by(id: params[:id])
    end

    def create
        perfume = Perfume.new(perfume_params)
        if perfume.save
            flash[:notice] = "診断が完了しました"
            redirect_to perfume_path(perfume.id)
        else
            redirect_to :action => "new"
        end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:question1, :question2, :question3, :question4)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @tweets = Tweet.all.order(created_at: :desc) # 全てのツイートを新しい順に取得
    # タグでの絞り込み検索のロジック（これはこのままでOK）
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          tag_tweets = Tag.find_by(name: key).tweets
          @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
        end
      end
    end
    if params[:tag]
      Tag.create(name: params[:tag])
    end
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to root_path, notice: '投稿が完了しました。'
    else
      render :new
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to tweet_path(tweet.id), notice: '投稿を更新しました。'
    else
      render :edit
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path, notice: '投稿を削除しました。'
  end
  def list
    @tweets = Tweet.all.order(created_at: :desc) # 全てのツイートを新しい順に取得
    # タグでの絞り込み検索のロジック（これはこのままでOK）
    if params[:tag_ids]
      @tweets = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          tag_tweets = Tag.find_by(name: key).tweets
          @tweets = @tweets.empty? ? tag_tweets : @tweets & tag_tweets
        end
      end
    end
    if params[:tag]
      Tag.create(name: params[:tag])
    end
  end
  private
  # private の下には、この tweet_params だけを記述します
  def tweet_params
    # チェックボックスから送られてくる tag_ids を配列として許可します
    params.require(:tweet).permit(:name, :price, :detail, :image, tag_ids: [])
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def getPercent(number) 
        if number.present?
            calPercent = number/5.to_f * 100
            # calPercent = number/10.to_f * 100
            #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
            percent = calPercent.round
            #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
            return percent.to_s
        else
            return 0
        end
    end
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mvc" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
 <header>
  <h1>GeekTwitter</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>

</html>

app/views/perfumes/index.html.erb
<h1>香水診断スタート</h1>
<%= link_to "診断を始める", new_perfume_path, class: "link" %>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">
        <div class="col-12">
            <p>Q1. どちらかと言うと…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">じっくり考える方だ</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">考えるより行動する方だ</label>
        </div>
        <div class="col-12">
            <p>Q2. 自分の価値観として近い方は…</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">周りの人と違う存在でありたい</label>
            <%= f.radio_button :question2, "2", id: "custom_id4" %>
            <label for="custom_id4">周りと同じでいたい</label>
        </div>   
        <div class="col-12">
            <p>Q3. 人と接するときは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">相手の話をよく聞く方だ</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">自分の話をよくする方だ</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 大切にしたいのは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">論理性だ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">情緒だ</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの香りは…</p>
</div>
<div class="perfume-container">
  <% case [@perfume.question1, @perfume.question2, @perfume.question3, @perfume.question4] %>
  <% when ["1", "1", "1", "1"] %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
  <% when ["1", "1", "1", "2"] %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>
  <% when ["1", "1", "2", "1"] %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>
  <% when ["1", "1", "2", "2"] %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>
  <% when ["1", "2", "1", "1"] %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>
  <% when ["1", "2", "1", "2"] %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>
  <% when ["1", "2", "2", "1"] %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>
  <% when ["1", "2", "2", "2"] %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  <% when ["2", "1", "1", "1"] %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>
  <% when ["2", "1", "1", "2"] %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>
  <% when ["2", "1", "2", "1"] %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>
  <% when ["2", "1", "2", "2"] %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>
  <% when ["2", "2", "1", "1"] %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>
  <% when ["2", "2", "1", "2"] %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>
  <% when ["2", "2", "2", "1"] %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>
  <% when ["2", "2", "2", "2"] %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>
  <% end %>
</div>
<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :size => 30 %>
  <%= f.label :値段  %>
    <%= f.number_field :price, :size => 10 %>
     <%= f.label :detail  %>
    <%= f.text_area :detail, :size => "30x2" %>
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>
<%= link_to "診断を始める", new_perfume_path, class: "link" %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <%= link_to "新規投稿へ", new_tweet_path %>
  <% end %>
<% end %>
 <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
  <% end %>
  <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
 <% end %>
     <%= link_to "一覧へ", tweet_list_path %>

app/views/tweets/list.html.erb
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <% if t.image.attached? %>
          <%= image_tag t.image, size: '250x200'%>
      <% end %>

         <%= t.name %>
         <% t.tags.each do |tag| %> 
          <span><%= tag.name %></span>
         <% end %>
         <%= t.price %>
         <%= t.detail %>
         <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.admin? %>
         <%= link_to "管理者用編集", edit_tweet_path(t.id) %>
         <%= link_to "管理者用削除", tweet_path(t.id), method: :delete %> 
    </div>
       <% end %> 
  <% end %>

 <%= link_to "トップページに戻る", tweets_path %>

 </div>

app/views/tweets/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>
  <div class='form-group'>
      <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class='form-check'>
              <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
              <% end %>
          </div>
      <% end %>
  </div>

  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :値段  %>
    <%= f.number_field :price, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :詳細  %>
    <%= f.text_area :detail, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :画像  %>
    <%= f.file_field :image %>
  </div>  

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.name %></p>
  <p><%= @tweet.price %></p>
  <p><%= @tweet.detail %></p>
</div>

<% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <h2>総合評価：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(c.overall) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span> 
      </h2>
    </div>

    <!--- 総合評価の星の部分終わり------->

    <!--- 授業レベルの星の部分 ------------>
    <div>
      <h2>授業レベル：
      <span class="star-rating">
        <span class="star-rating-front" style="width: <%= getPercent(c.level) %>%;">★★★★★</span>
        <span class="star-rating-back">★★★★★</span>
      </span>
      </h2>
    </div>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <h5>総合評価</h5>
      <div class="post_form">
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">最高</span>★</label>

        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>

        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>

        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>

        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
      </div>

      <h5>授業レベル</h5>
      <div class="post_form">
        <%= f.radio_button :level,  5 ,id: 'star6'%>
        <label for="star6"><span class="text">難しい</span>★</label>

        <%= f.radio_button :level,  4 ,id: 'star7'%>
        <label for="star7"><span class="text">やや難しい</span>★</label>

        <%= f.radio_button :level, 3 ,id: 'star8'%>
        <label for="star8"><span class="text">普通</span>★</label>

        <%= f.radio_button :level , 2 ,id: 'star9'%>
        <label for="star9"><span class="text">やや簡単</span>★</label>

        <%= f.radio_button :level , 1 ,id: 'star10'%>
        <label for="star10"><span class="text">簡単</span>★</label>
      </div>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "トップページに戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>
<%= link_to "一覧へ", tweet_list_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>